version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    - 5432:5432

    
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    
    
  consumer:
    build: consumer
    restart: on-failure
    volumes:
    - ./consumer:/apl
    links:
    - rabbitmq
